accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "accounts"

urlpatterns = [
    # writer views
    path('', views.admin_dashboard, name='admin_dashboard'),
    # path('<str:username>', views.user_article, name='user_article'),
    path('new/', views.new, name='new'),
    path('new/blog/', views.new_blog, name='new_blog'),
    path('new/link/', views.new_link, name='new_link'),
    
    path('blog/<slug:slug>/add_meta', views.blog_meta_description, name='blog_meta_description'),

    # Admin views
    path('blog/review', views.review_list, name='review_list'),
    path('blog/<slug:slug>/edit', views.edit_blog, name='edit_blog'),
	path('blog/<slug:slug>/review', views.review, name='review_article'),


    path('settings/', views.user_settings, name='user_settings'),
    path('settings/profile/edit', views.settings_profile_edit, name='settings_profile_edit'),

    # users
    # telegram
    path('connect_telegram', views.connect_telegram, name='connect_telegram'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    # user views 
    # path('', TemplateView.as_view(template_name='welcome.html'), name='index'),
    # path('', TemplateView.as_view(template_name='base_v2.html'), name='index'),
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.article, name='article'),
    
    # writer views
    path('user/<str:username>', views.user_article, name='user_article'),
    path('blog/new/blog', views.new_blog, name='new_blog'),
    path('blog/new/link', views.new_link, name='new_link'),
	path('blog/new/choose', views.choose_new_post_type, name='choose_new_post_type'),
    path('blog/<slug:slug>/add_meta', views.blog_meta_description, name='blog_meta_description'),

    # Admin views
    path('blog/review', views.review_list, name='review_list'),
    path('blog/<slug:slug>/edit', views.edit_blog, name='edit_blog'),
	path('blog/<slug:slug>/review', views.review, name='review_article'),

    # users

]

usersite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from django.views.generic.base import TemplateView
from core.views import post_api, quran_api#, catagory_api
from core.api.views import QuranAPIView

from accounts.views import (login_view, logout_view, register_view, telegram_bot)

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()

router.register('post', post_api, basename='post_api')
router.register('quran', quran_api, basename='quran_api')

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    
    # VISITOR INTERFACE
    path('quran/', include('core.api.urls', namespace='quran-view')),
    # path('quran/<slug:slug>/', QuranAPIView.as_view(), name='quran-view'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),    
    
    path('faq_v1/', TemplateView.as_view(template_name='faq.html'), name='faq_v1'),
    path('faq/', TemplateView.as_view(template_name='faq_v2.html'), name='faq_v2'),
    path('media/', TemplateView.as_view(template_name='media.html'), name='media'),
    path('about/', TemplateView.as_view(template_name='about_us_v2.html'), name='about'),
    path('roadmap/', TemplateView.as_view(template_name='roadmap_v2.html'), name='roadmap'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact'),
    
    # testing
    # path('login_v2/', TemplateView.as_view(template_name='accounts/login_v2.html'), name='base_v2'),

    # ADMIN INTERFACE
    path('login/',login_view, name='login' ),    
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('admin/', admin.site.urls),

    path('dashboard/', include('accounts.urls', namespace='dashboard')),

    # TELEGRAM BOT
    path('tbot/', telegram_bot, name='telegram_bot'),    

    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from .models import Profile
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)

User = get_user_model()

class ProfileForm(forms.ModelForm):
    phone_number = forms.CharField(label='Phone Number',widget = forms.TextInput(attrs={'placeholder': 'Please enter your phone number'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Please enter your bio within 500 characters'}))
    class Meta:
        model = Profile
        fields = [
            'phone_number',
            'bio',
        ]




class UserLoginForm(forms.Form):
    username = forms.CharField(label='',widget = forms.TextInput(attrs={'placeholder': 'User Name', 'class':'form-control'}))
    password = forms.CharField(label='',widget = forms.PasswordInput(attrs={'placeholder': 'Password', 'class':'form-control'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password.")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer Active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='',widget = forms.TextInput(attrs={'placeholder': 'Email Address', 'class':'form-control'}))
    username = forms.CharField(label='',widget = forms.TextInput(attrs={'placeholder': 'User Name', 'class':'form-control'}))
    password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class':'form-control'}))

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password'
        ]

    def clean_email2(self):
        email = self.cleaned_data.get('email')
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email

accounts/views.py
import json
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
)
from django.contrib.auth.decorators import user_passes_test

from django.conf import settings
from django.http import Http404, HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect

from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt

from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from .models import Profile, accountCode
from core.forms import ArticleForm, MetaTagForm, ReviewArticle, LinkForm, ReviewLink
from core.models import Post, catagories
from bots.telegram import send_message, send_pair_url, successful_connection, check_existing_user, check_existing_code, already_connnected, send_help, send_help_user, profile, coming_soon, please_pair
from django.contrib.auth.models import User


def login_view(request):
	key = request.GET.get('key')
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		login(request,user)
		# change redirect to profile page
		if key:
			return redirect(reverse('dashboard:connect_telegram') + '?key={}'.format(key))
		else:
			return redirect(reverse('dashboard:admin_dashboard'))
	context = {
		'title' : 'Please Log in',
		'sub_title' : 'Enter your credentials',
		'button_text' : 'Login',
		'production' : settings.PRODUCTION,
		"form" : form,
	}
	return render(request, 'accounts/login_v2.html', context)

def register_view(request):
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get("password")
		user.set_password(password)
		user.save()

		new_user = authenticate(username=user.username, password=password)
		login(request, new_user)
		# change redirect to profile page
		# return redirect("/")
		return redirect(reverse('dashboard:settings_profile_edit') + '?next=setup')
	context = {
		'title' : 'Register New Account',
		'sub_title' : 'Welcome to the community. Please fill the form to create your account',
		'button_text' : 'Register',
		'production' : settings.PRODUCTION,	
		"form":form,
	}
	return render(request, 'accounts/login_v2.html', context)

def logout_view(request):
	logout(request)
	return redirect('/')

@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def user_settings(request):
	context = {
		'title' : 'Settings',
		'production' : settings.PRODUCTION,
	}
	return render(request, 'accounts/user_settings.html', context)

@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def settings_profile_edit(request):
	next_page = request.GET.get('next')

	existing_details = Profile.objects.get(user=request.user)
	form = ProfileForm(request.POST or None, instance=existing_details)	
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		# messages.success(request, "Successfully Created")
		if next_page == 'setup':
			return redirect(reverse('dashboard:new'))
		else:
			return redirect(reverse('dashboard:user_settings'))

	context = {
		'title' : 'Edit bio',
		'button_text' : 'Confirm',
		'blog_title' : 'Edit your profile details',
		'production' : settings.PRODUCTION,
		'form' : form,
	}
	return render(request, 'accounts/settings_editor.html', context)



# ------------ T E L E G R A M    B O T
@csrf_exempt
def telegram_bot(request):
	# print('recieve the message.')
	try:
		# print('trying to find json')
		json_message = json.loads(request.body)

	except json.decoder.JSONDecodeError as err:
		print("Found no Json. here's your page")
		return HttpResponse("looking for something? Well, it's not here.")
	
	# write the code here to use the following data from JSON Response
	sender_id		= json_message['message']['from'].get('id')
	update_id		= json_message.get('update_id')
	message_text	= json_message['message'].get('text')
	message_date	= json_message['message'].get('date')

	first_name		= json_message['message']['from'].get('first_name')
	last_name		= json_message['message']['from'].get('last_name')

	registered_user = check_existing_user(sender_id)
	requested_user = check_existing_code(sender_id)

	if message_text == '/start':
		reply = send_message('', message_text, '', sender_id)
	
	# pair telegram account to website account
	elif message_text == '/pair':
		if registered_user:
			reply = already_connnected(sender_id)
		else:
			reply = send_pair_url(sender_id)
	
	# view website account profile
	elif message_text == '/profile':
		if registered_user:
			reply = profile(sender_id)
		else:
			reply = please_pair(sender_id)
	
	# feature coming soon
	elif message_text == '/unpair' or '/mystatus' or '/editprofile':
		if registered_user:
			reply = coming_soon(sender_id)
		else:
			reply = please_pair(sender_id)
	
	# send help
	elif message_text == '/help':
		if registered_user:
			reply = send_help_user(sender_id)
		else:		
			reply = send_help(sender_id)
	
	else:
		reply = send_message("hey {} {}".format(first_name, last_name), message_text, message_date, sender_id)

	return JsonResponse(reply, safe=False)

def connect_telegram(request):
	# get the code from url
	verify_code = request.GET.get('key')
	# print(verify_code)	
	# using the code, get the connected chat_id
	try:
		chat_id = accountCode.objects.get(verify_code=verify_code).chat_id
	
		# get current user details
		user = User.objects.get(username=request.user)


		# update their profile to inclide chat_id
		user.profile.chat_id = chat_id
		# save
		user.save()

		successful_connection(chat_id)
		# get telegram chat_id connected to key from accounts.accountCode, using verify_code
		# if not empty. set the Profile.chat_id with this chat_id
		message = 'Your Simple wedding Account is now linked to this Telegram account.'
		status = True

	except accountCode.DoesNotExist:
		chat_id = None
		message = 'Connection failed. You will soon recieve a new link on telegram.'
		# alert Superuser.
		# send new link to connect
		status = False

	

	context = {
		'title' : 'Connecting to Telegram',
		'message' : message,
		'status' : status,
		'production' : settings.PRODUCTION,

	}

	return render(request, 'accounts/telegram_confirm.html', context)

# ------------ A D M I N    I N T E R F A C E     P A G E S 

# User admin Dashboard
@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def admin_dashboard(request):
	article = Post.objects.filter(user__username=request.user.username)

	# get all blogs
	# get all topics
	# get all links

	context = {
		'production' : settings.PRODUCTION,
		'blogs' : article,
		# 'editable' : editable,
	}
	return render(request, 'accounts/admin_dashboard_v2.html', context)

# Choose what type of post you want to post
@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def new(request):
	context = {
		'title' : 'Submit New Article',
		'button_text' : 'Submit For Review',
		'production' : settings.PRODUCTION,
	}
	return render(request, 'accounts/new.html', context)	


# Add new blog page
@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def new_blog(request):
	form = ArticleForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# messages.success(request, "Successfully Created")
		# return HttpResponseRedirect(instance.get_absolute_url())
		return redirect(reverse('dashboard:blog_meta_description', kwargs={'slug':instance.slug}))



	context = {
		'title' : 'Submit New Article',
		'button_text' : 'Submit For Review',
		'production' : settings.PRODUCTION,
		'form' : form,
	}
	return render(request, 'accounts/blog_editor.html', context)


# Add new link page
@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def new_link(request):

	form = LinkForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		link = instance.link

		# fetch the title
		# fetch the meta_description
		title, meta_description, link_detail = fetch_details_from_link(link)

		instance.title = title
		instance.meta_description = meta_description
		instance.detail = link_detail
		instance.save()
		# messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
		# return redirect(reverse('core:blog_meta_description', kwargs={'slug':instance.slug}))
		# return redirect(reverse('core:new_link'))

	context = {
		'title' : 'Submit New Link',
		'button_text' : 'Submit For Review',
		'production' : settings.PRODUCTION,
		'form' : form,
	}
	return render(request, 'accounts/new_link.html', context)	

# Edit blog page
@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('login'))
def edit_blog(request, slug=None):
	post = Post.objects.get(slug=slug)
	if request.user==post.user or request.user.is_staff:# or not request.user.is_superuser:
		pass
	else:
		raise Http404

	form = ArticleForm(request.POST or None, instance=post)
	if form.is_valid():
		instance = form.save(commit=False)
		if not request.user.is_staff: #turn blog as unpublished if the blog is edited by non-admin
			instance.publish=False
		instance.save()
		# messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())


	context = {
		'title' : 'Edit Article',
		'button_text' : 'Submit For Review',
		'blog_title' : post.title,		
		'production' : settings.PRODUCTION,
		'form' : form,
	}
	return render(request, 'accounts/blog_editor.html', context)

# TODO
# DONE Add url to meta description
# DONE Create FORM
# DONE Create a meta-editor page
# DONE After new_blog, redirect user to here.
# Add character count on form using JQuery or something

accounts/templates/accounts/admin_dashboard_v2.html
{% extends 'accounts/admin_base.html' %}
{% load static %}



{% block title %} Welcome {% if request.user.get_full_name %}{{request.user.get_full_name}}{% else %}{{request.user.username}}{% endif %} {{block.super}} {% endblock %}

{% block content %}
<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Dashboard</li>
</ol> 
<div class="card mb-4">
	<div class="card-header"><i class="fas fa-table mr-1"></i>My Submissions</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table" id="dataTable" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Title</th>
						<th>Status</th>
						<th>Last Update</th>
						<th>View</th>
						<th>Edit</th>
						<th>Meta</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Title</th>
						<th>Status</th>
						<th>Last Update</th>
						<th>View</th>
						<th>Edit</th>
						<th>Meta</th>
						<th>Delete</th>
					</tr>
				</tfoot>
				<tbody>
					{% for blog in blogs %}
					<tr>
						<td>
							<!-- <span class="badge badge-pill badge-primary">
								{{blog.catagory}}
							</span><br> -->
							{{blog.title}}
						</td>
						<td>
							{% if blog.publish %}
							<span class="badge badge-primary">Published</span>
							{% else %}
							<span class="badge badge-secondary">Draft</span>
							{% endif %}
						</td>
						<td>
							{{blog.updated|date:'d M Y'}}<br>
							<!-- {{blog.updated|date:'g:i a'}}<br> -->
							<!-- {{blog.updated|date:'l'}}<br> -->
						</td>
						<td>
							<a style="margin: 5px" href="{% if blog.link %}{{blog.link}}{% else %}{% url 'core:article' blog.slug %}{% endif %}" class="btn btn-outline-primary">
								<i class="fas fa-eye"></i>
							</a>
						</td>
						<td>
							<a style="margin: 5px" href="{% url 'dashboard:edit_blog' blog.slug %}" class="btn btn-outline-secondary">
								<i class="fas fa-edit"></i>
							</a>
						</td>
						<td>
							<a style="margin: 5px" href="{% url 'dashboard:blog_meta_description' blog.slug %}" class="btn btn-outline-secondary">
								<i class="fas fa-info-circle"></i>
							</a>
						</td>
						<td>
							<a style="margin: 5px" href="" class="btn btn-outline-danger disabled">
								<i class="fas fa-trash"></i>
							</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/layoutSidenav.html
<div id="layoutSidenav_nav">
	<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
		<div class="sb-sidenav-menu">
			<div class="nav">
				<div class="sb-sidenav-menu-heading">Home</div>
				<a class="nav-link" href="{% url 'dashboard:admin_dashboard' %}">
					<div class="sb-nav-link-icon">
						<i class="fas fa-tachometer-alt"></i>
					</div>
					Dashboard
				</a>
				<div class="sb-sidenav-menu-heading">Admin</div>
				<a class="nav-link" href="{% url 'dashboard:review_list' %}">
					<div class="sb-nav-link-icon">
						<i class="fas fa-chart-area"></i>
					</div>
					View Submissions
				</a>
			
				<div class="sb-sidenav-menu-heading">Writer</div>
				
				<!-- Submit -->
				<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseWriter" aria-expanded="false" aria-controls="collapseWriter">
					<div class="sb-nav-link-icon">
						<i class="fas fa-columns"></i>
					</div>

					Submit New
					<div class="sb-sidenav-collapse-arrow">
						<i class="fas fa-angle-down"></i>
					</div>
				</a>
				<div class="collapse" id="collapseWriter" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
					<nav class="sb-sidenav-menu-nested nav">
						<a class="nav-link" href="{% url 'dashboard:new_blog' %}">Write Article</a>
						<a class="nav-link" href="{% url 'dashboard:new_link' %}">Share Link</a>
						<a class="nav-link disabled" href="/">Create Topic Idea</a>
					</nav>
				</div>
				<!-- <a class="nav-link disabled " href="/">
					<div class="sb-nav-link-icon">
						<i class="fas fa-chart-area"></i>
					</div>
					Drafts
				</a> -->
				<!-- <a class="nav-link disabled " href="/">
					<div class="sb-nav-link-icon">
						<i class="fas fa-chart-area"></i>
					</div>
					Submitted
				</a> -->
				<!-- End of submit -->

				<div class="sb-sidenav-menu-heading">Website</div>
				<a class="nav-link" href="{% url 'core:index' %}">
					<div class="sb-nav-link-icon">
						<i class="fas fa-chart-area"></i>
					</div>
					Homepage
				</a>

				<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
					<div class="sb-nav-link-icon">
						<i class="fas fa-columns"></i>
					</div>

					Pages
					<div class="sb-sidenav-collapse-arrow">
						<i class="fas fa-angle-down"></i>
					</div>
				</a>
				<div class="collapse" id="collapsePages" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
					<nav class="sb-sidenav-menu-nested nav">
						<a class="nav-link" href="{% url 'faq_v2' %}">FAQ</a>
						<a class="nav-link" href="{% url 'about' %}">About Us</a>
						<a class="nav-link" href="{% url 'media' %}">Media</a>
						<a class="nav-link" href="{% url 'roadmap' %}">RoadMap</a>
						<a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
					</nav>
				</div>
				<!-- 
				<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
					<div class="sb-nav-link-icon">
						<i class="fas fa-book-open"></i>
					</div>

					Pages
					<div class="sb-sidenav-collapse-arrow">
						<i class="fas fa-angle-down"></i>
					</div>
				</a>
				<div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
					<nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
						<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
							Authentication
							<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i>
							</div>
						</a>
						<div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
							<nav class="sb-sidenav-menu-nested nav">
								<a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a>
								<a class="nav-link" href="password.html">Forgot Password</a>
							</nav>
						</div>
						<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
							Error
							<div class="sb-sidenav-collapse-arrow">
								<i class="fas fa-angle-down"></i>
							</div>
						</a>
						<div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
							<nav class="sb-sidenav-menu-nested nav">
								<a class="nav-link" href="401.html">
									401 Page
								</a>
								<a class="nav-link" href="404.html">
									404 Page
								</a>
								<a class="nav-link" href="500.html">
									500 Page
								</a>
							</nav>
						</div>
					</nav>
				</div>
 				-->
			</div>
		</div>
		<div class="sb-sidenav-footer">
			<div class="small">Logged in as:</div>
			{% if request.user.get_full_name %}
			{{request.user.get_full_name}}
			{% else %}
			{{request.user.username}}
			{% endif %}
		</div>
	</nav>
</div> 
<!-- /End of Side Navbar -->

accounts/templates/accounts/new.html
{% extends 'accounts/admin_base.html' %}
{% load static %}


{% block title %}
Choose new Submission {{block.super}}
{% endblock %}

{% block head_extras %}
<style type="text/css">
	.item-box{
		margin-bottom: 30px;
		padding: 20px;
		border-radius: 5px;
		outline-color: #dddddd;
	}

	.item-box:hover{
		box-shadow: 0px 5px 5px #84CD99;
	}

</style>
{% endblock %}

{% block content %}
<h1 class="mt-4">Choose what you want to submit</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item">
		<a href="{% url 'dashboard:admin_dashboard' %}">
			Dashboard
		</a>
	</li>
	<li class="breadcrumb-item active">New Submission</li>
</ol> 



<section class="col-lg-6 offset-lg-3 col-sm-12 col-md-12">
	<div>
		<!-- <p class="lead">Choose what you want to submit</p> -->

		<div class="row item-box">
			<p class="disabled">
				<h2>Article Title</h2>
				<p style="color: grey" class="lead"><b>Coming soon.</b><br>
				Submit An article idea or suggestion. Anyone can write articles on the topics you suggest</p>
				</[>
			</div>
			<div class="row item-box">
				<a href="#" data-toggle="modal" data-target="#newArticle">
					<h2>Article</h2>
					<p class="lead">Write an Article on any topic.</p>
				</a>
			</div>
			<div class="row item-box">
				<a href="{% url 'dashboard:new_link' %}">
					<h2>Link</h2>
					<p class="lead">Submit Links to display on the articles page</p>
				</a>
			</div>
		</div>
	</section>



	<!-- Button trigger modal -->
<!-- 
<button type="button" class="btn btn-primary" >
  Launch demo modal
</button>
-->

<!-- Modal -->
<div class="modal fade" id="newArticle" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalCenterTitle">The article topic</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div>

				<div class="modal-body">
					<div class="row item-box">
						<a href="{% url 'dashboard:new_blog' %}">
							<h2>New topic</h2>
						</a>
					</div>
					<div class="row item-box disabled">
						<p class="disabled">
							<h2 style="color: gray;">Pick title from suggestions</h2>
						</p>
					</div>
				</div>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}