core/api/urls.py
from .views import QuranAPIView
from django.urls import path, include
from django.conf import settings

# from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token

app_name = 'quran-api'

urlpatterns = [
	path('<slug:slug>/', QuranAPIView.as_view(), name='quran-view'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    # user views 
    # path('', TemplateView.as_view(template_name='welcome.html'), name='index'),
    # path('', TemplateView.as_view(template_name='base_v2.html'), name='index'),
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.article, name='article'),
    
    # writer views
    path('user/<str:username>', views.user_article, name='user_article'),
    path('blog/new/blog', views.new_blog, name='new_blog'),
    path('blog/new/link', views.new_link, name='new_link'),
	path('blog/new/choose', views.choose_new_post_type, name='choose_new_post_type'),
    path('blog/<slug:slug>/add_meta', views.blog_meta_description, name='blog_meta_description'),

    # Admin views
    path('blog/review', views.review_list, name='review_list'),
    path('blog/<slug:slug>/edit', views.edit_blog, name='edit_blog'),
	path('blog/<slug:slug>/review', views.review, name='review_article'),

    # users

]

usersite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from django.views.generic.base import TemplateView
from core.views import post_api, quran_api#, catagory_api
from core.api.views import QuranAPIView

from accounts.views import (login_view, logout_view, register_view, telegram_bot)

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()

router.register('post', post_api, basename='post_api')
router.register('quran', quran_api, basename='quran_api')

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    
    # VISITOR INTERFACE
    path('quran/', include('core.api.urls', namespace='quran-view')),
    # path('quran/<slug:slug>/', QuranAPIView.as_view(), name='quran-view'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),    
    
    path('faq_v1/', TemplateView.as_view(template_name='faq.html'), name='faq_v1'),
    path('faq/', TemplateView.as_view(template_name='faq_v2.html'), name='faq_v2'),
    path('media/', TemplateView.as_view(template_name='media.html'), name='media'),
    path('about/', TemplateView.as_view(template_name='about_us_v2.html'), name='about'),
    path('roadmap/', TemplateView.as_view(template_name='roadmap_v2.html'), name='roadmap'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact'),
    
    # testing
    # path('login_v2/', TemplateView.as_view(template_name='accounts/login_v2.html'), name='base_v2'),

    # ADMIN INTERFACE
    path('login/',login_view, name='login' ),    
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('admin/', admin.site.urls),

    path('dashboard/', include('accounts.urls', namespace='dashboard')),

    # TELEGRAM BOT
    path('tbot/', telegram_bot, name='telegram_bot'),    

    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings

from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

from core.utils import random_string_generator
from django.utils.text import Truncator


class quran(models.Model):
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    
    slug = models.CharField(max_length=10, unique=True)
    # a counter to see how many times each aiyath is requested
    request = models.IntegerField(default=0)
    
    # aiyath number. surah 2 and aiyath 1 will be 8. because surah fatiha has 7 aiyath
    aiyath_number = models.IntegerField() #<- use this to get quran audio url
    
    # quran aiyath
    text = models.CharField(max_length=7000) #<= the longest aiyah (2:282) is 1200 char long in arabic. and 6300 long in byte text. not sure which willbe used to share here 
    
    # quran audio
    audio_64 = models.CharField(max_length=100)
    audio_128 = models.CharField(max_length=100)

    surah_number = models.IntegerField()
    surah_name = models.CharField(max_length=200)
    surah_englishName = models.CharField(max_length=100)
    surah_englishNameTranslation = models.CharField(max_length=500)
    surah_numberOfAyahs = models.IntegerField() 
    surah_revelationType = models.CharField(max_length=100)

    # aiyath number
    numberInSurah = models.IntegerField()
    juz = models.IntegerField()
    manzil = models.IntegerField()
    page = models.IntegerField()
    ruku = models.IntegerField()
    hizbQuarter = models.IntegerField()
    sajda = models.BooleanField(default=False)

    def __str__(self):
        return str(self.surah_englishName) + ":" + str(self.numberInSurah)

    def save(self, *args, **kwargs):
        self.slug = str(self.surah_number) +"-"+ str(self.numberInSurah)
        super(quran, self).save(*args, **kwargs) # Call the "real" save() method.

    def existing_slug(self, *args, **kwargs):
        return str(self.surah_number) +":"+ str(self.numberInSurah)
    # def get_absolute_url(self):
    #     return reverse("blogs:detail", kwargs={"slug" : self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]
        # unique_together = ('surah_number', 'numberInSurah')        

# Create your models here.
default_meta_description = 'Please enter meta description for better visibility'
class catagories(models.Model):
    catagory_name = models.CharField(max_length=20)
    description = models.TextField(max_length=160)

    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.catagory_name

    # def get_absolute_url(self):
    #     return reverse("blogs:detail", kwargs={"slug" : self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_default_slug(title):
    return slugify((Truncator(title).chars(200) +'-'+ random_string_generator(size=4)))


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)

    # slug = models.SlugField(unique=True) # enable then when we need links
    title = models.CharField(max_length=300)
    link = models.CharField(max_length=2200, blank=True)
    detail = models.TextField(max_length=22000)
    meta_description = models.TextField(max_length=160, default=default_meta_description)
    slug = models.SlugField(max_length=200, unique=True)
    catagory = models.ForeignKey(catagories, related_name='posts', default=1, on_delete=models.CASCADE)

    publish = models.BooleanField(default=False)

    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        """
        Slugify name if it doesn't exist. IMPORTANT: doesn't check to see
        if slug is a dupe!
        """
        if not self.slug:
            self.slug = create_default_slug(self.title)
        super(Post, self).save(*args, **kwargs)



    def get_absolute_url(self):
        return reverse("core:article", kwargs={"slug" : self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

################   P R E    S A V E    S T U F F     F O R     S L U G     C R E A T I O N
def create_slug(instance, new_slug=None):
    if new_slug is not None:
        slug = new_slug
    else:
        slug = slugify((Truncator(instance.title).chars(200) +'-'+ random_string_generator(size=4)))
    exists = Post.objects.filter(slug=slug).order_by("-id").exists()
    if exists:
        a = slug.split('-')
        a_list = a[:-1] #remove the last element from this list.
        slug = "-".join(a_list)        
        new_slug = "{slug}-{randstr}".format(slug=slug,randstr=random_string_generator(size=4))
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_jd_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_jd_receiver, sender=Post)

core/forms.py
from django import forms
from .models import Post, catagories
from pagedown.widgets import PagedownWidget
from django.core.validators import URLValidator



class ArticleForm(forms.ModelForm):
    title = forms.CharField()
    detail = forms.CharField(widget=PagedownWidget())
    # tags = forms.ModelMultipleChoiceField(queryset = taggers.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Post
        fields = [
            "title",
            "detail",
            # "tags"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        article_placeholder = '''       Start writing Your Article Here
        
        How to Format!
        ## for Heading
        ### for subheading

        Example 

        ## how to bake
        ### Start here
        ### follow the list
        1. item 1
        2. item 3
        3. item 3
        '''
        self.fields['title'].widget.attrs['placeholder'] = 'The Title'
        self.fields['detail'].widget.attrs['placeholder'] = article_placeholder


class MetaTagForm(forms.ModelForm):
    meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

class ReviewArticle(forms.ModelForm):
    title = forms.CharField()
    meta_description = forms.CharField(widget=forms.Textarea)
    detail = forms.CharField(widget=PagedownWidget())
    # tags = forms.ModelMultipleChoiceField(queryset = taggers.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Post
        fields = [
            "title",
            "meta_description",
            "detail",
            "publish",
            # "tags"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        article_placeholder = '''       Start writing Your Article Here
        
        How to Format!
        ## for Heading
        ### for subheading

        Example 

        ## how to bake
        ### Start here
        ### follow the list
        1. item 1
        2. item 3
        3. item 3
        '''
        self.fields['title'].widget.attrs['placeholder'] = 'The Title'
        self.fields['detail'].widget.attrs['placeholder'] = article_placeholder
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

class LinkForm(forms.ModelForm):
    # title = forms.CharField()
    link = forms.CharField()
    # meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            # "title", <-- Will be parsed by 
            "link",
            # "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].widget.attrs['placeholder'] = "Paste your link here with https:// or http://"
        # self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"


class ReviewLink(forms.ModelForm):
    title = forms.CharField()
    link = forms.CharField()
    meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            "title",
            "link",
            "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].widget.attrs['placeholder'] = "Paste your link here"
        self.fields['title'].widget.attrs['placeholder'] = "Write the title"
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

core/api/views.py
from rest_framework import generics
from core.models import quran

from .serializers import QuranSerializer

class QuranAPIView(generics.RetrieveAPIView):
	lookup_field 			=	'slug'
	serializer_class 		=	QuranSerializer	
	queryset				=	quran.objects.all()

core/views.py
from django.conf import settings
# from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User


from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy

# importing views
from .models import Post, catagories, quran
from .forms import ArticleForm, MetaTagForm, ReviewArticle, LinkForm, ReviewLink

# rest framework stuff
from rest_framework import viewsets


from .serializers import CatagorySerializer, PostSerializer, QuranSerializer

class quran_api(viewsets.ModelViewSet):
	# add serializer from QuranSerializer
	queryset = quran.objects.all()
	serializer_class = QuranSerializer

# class catagory_api(viewsets.ModelViewSet):
# 	queryset = catagories.objects.all()
# 	serializer_class = CatagorySerializer

class post_api(viewsets.ModelViewSet):
	queryset = Post.objects.all()
	serializer_class = PostSerializer

# ------------ V I S I T O R    I N T E R F A C E     P A G E S 

def index(request):
	blogs = Post.objects.filter(publish=True)[:5]

	context = {
		'production' : settings.PRODUCTION,
		'blogs': blogs,
	}
	return render(request, 'welcome_v2.html', context)

def blog(request):
	# import data from models
	links = Post.objects.filter(publish=True)

	context = {
		'production' : settings.PRODUCTION,
		'links' : links,
	}
	return render(request, 'core/blog_v2_list.html', context)

def article(request, slug=None):
	editable = False
	# try:
	# use this as try and except once there is 404 page
	if request.user.is_authenticated:
		article = get_object_or_404(Post, slug=slug)
	else:
		article = get_object_or_404(Post, slug=slug, publish=True)
	# except Exception as e:
	# 	return render(request, 'error_404.html')
	if request.user.is_authenticated:# or not request.user.is_staff or not request.user.is_superuser:
		if request.user==article.user or request.user.is_staff:
			editable = True

	# check article is link
	

	context = {
		'production' : settings.PRODUCTION,
		'article' : article,
		'editable' : editable,
	}
	if article.meta_description == 'youtube':
		return render(request, 'core/blog_v2_youtube.html', context)
	else:
		return render(request, 'core/blog_v2_detail.html', context)		


# TODO
# DONE Show all blog by user
# DONE if request.user == username, then show even publish=true & false blogs.
def user_article(request, username=None):
	this_user=User.objects.filter(username=username)
	if this_user.exists():
		if username == request.user.username:
			article = Post.objects.filter(user__username=username)
		else:
			article = Post.objects.filter(publish=True, user__username=username)
		# print(article)
	else:
		return Http404

	# if request.user.is_authenticated:# or not request.user.is_staff or not request.user.is_superuser:
		# if request.user==article.user or request.user.is_staff:
			# editable = True

	context = {
		'production' : settings.PRODUCTION,
		'links' : article,
		# 'editable' : editable,
	}
	return render(request, 'core/blog_list.html', context)

core/templates/core/blog_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{article.title}} Simple wedding Movement
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h1 class="mt-5" style="color: #565656">{{article.title}}</h1>
			{% if article.publish == False %}
			<span style="color: red"><b>WAITING FOR APPROVAL</b></span>
			{% endif %}

		</div>
	</div>
</div>
<section class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1 col-md-8 offset-md-2">
	
	{% if editable %}
	<div class="card">
		<div class="card-body">
			{% if request.user.is_staff %}
			<div class="float-right">
				<a href="{% url 'core:review_article' article.slug %}" class="btn btn-success" >Review</a>
			</div>
			{% else %}
			<div class="float-left">
				<a href="{% url 'core:edit_blog' article.slug %}" class="btn btn-outline-primary" >Edit Article</a>
				<a href="{% url 'core:blog_meta_description' article.slug %}" class="btn btn-outline-info" >Edit Description</a>
			</div>
			{% endif %}
		</div>
	</div>
	{% endif %}

	<div class="card">
		<div class="card-body">
			<!-- <h5 class="card-title">Special title treatment</h5> -->
			<div class="card-text content-markdown">{{article.detail}}</div>
		</div>
		<div class="card-footer text-muted">
			<div class="d-flex w-100 justify-content-between">
				<small class="extra-text">By <a href="{% url 'core:user_article' article.user %}">{{article.user}}</a></small>
				<small class="extra-text">posted {{article.timestamp|timesince}} ago</small>
			</div>
		</div>
	</div>

	{% if editable %}
	<div class="card">
		<div class="card-body">
			{% if request.user.is_staff %}
			<div class="float-right">
				<a href="{% url 'core:review_article' article.slug %}" class="btn btn-success" >Review</a>
			</div>
			{% else %}
			<div class="float-left">
				<a href="{% url 'core:edit_blog' article.slug %}" class="btn btn-outline-primary" >Edit Article</a>
				<a href="{% url 'core:blog_meta_description' article.slug %}" class="btn btn-outline-info" >Edit Description</a>
			</div>
			{% endif %}
		</div>
	</div>
	{% endif %}
</section>


{% endblock %}

core/templates/core/blog_list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Blogs | Simple wedding Movement
{% endblock %}

{% block head_extras %}
<style type="text/css">
  .item-box{
    background-color: #B3E0C0;
    margin-bottom: 30px;
    padding: 20px;
    border-radius: 5px;
    outline-color: #dddddd;
  }

  .item-box:hover{
    background-color: #A4DAB3;
    box-shadow: 0px 5px 5px #84CD99;
  }
  .video-container {
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 56.25%;
    margin-bottom: 30px;
  }
  .youtube-video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5" style="color: #565656">Your Guide to a Simple Wedding</h1>
      <p class="lead">When Wedding are simple, life becomes easy.</p>
      <ul class="list-unstyled">
        <li><a href="tel:+918008245395">Call us</a></li>
      </ul>
    </div>
  </div>
</div>

<section class="col-lg-6 offset-lg-3 col-sm-12 col-md-12">
  <div>
    {% for link in links %}
    
    <div class="row item-box">
      <div class="col">
        <div class="row">

          {% if link.meta_description == 'youtube' %}
          <!-- if post is youtube link, show the embedded player -->
          <div class="video-container">
            <iframe src="https://www.youtube.com/embed/{{link.detail}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" class="youtube-video" allowfullscreen></iframe>
          </div>

          {% else %}


          <a href="{% if link.link %}{{link.link}}{% else %}{% url 'core:article' link.slug %}{% endif %}">
            <h2>{{link.title}}</h2>
            <p class="lead">{{link.meta_description}}</p>
          </a>

          {% endif %}
        </div>
        <div class="row text-muted">
          {{link.catagory}} | By &nbsp;<a href="{% url 'core:user_article' link.user %}"> {{link.user}}</a> &nbsp;| {{link.timestamp|timesince}} ago
        </div>
      </div>
    </div>

    <!-- <a href="{% url 'core:user_article' link.user %}" class="link-box list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <small class="extra-text">By {{link.user}}</small>
        <small class="extra-text">{{link.timestamp|timesince}} ago</small>
      </div>
    </a> -->


    

    {% empty %}
    <a href="" class="list-group-item list-group-item-action flex-column align-items-start active">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Whatsapp Group</h5>
        <small>Join 100+ People</small>
      </div>
      <p class="mb-1"></p>
      <small>Take part in our daily Discussion and learn more about why wedding needs to be simple.</small>
    </a>
    {% endfor %}
  </div>
</section>
{% endblock %}

<!-- 
<iframe width="100%" height="fill" src="https://www.youtube.com/embed/nxf41fMX_Y4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->

core/templates/core/blog_v2_detail.html
{% extends 'base_v2.html' %}
{% load static %}


{% block title %} {{article.title}} | {{block.super}}{% endblock %}

{% block content %}
<!-- <h3 class="pb-4 mb-4 font-italic border-bottom">
From the Firehose
</h3> -->
<div class="blog-post">
	<h2 class="blog-post-title">{{article.title}}</h2>
	<p class="blog-post-meta">{{article.timestamp|date:"D d M Y"}} by <a href="{% url 'core:user_article' article.user %}">{{article.user}}</a></p>
	<div class="content-markdown">{{article.detail}}
	</div>

</div><!-- /.blog-post -->
{% endblock %}

core/templates/core/blog_v2_youtube.html
{% extends 'base_v2.html' %}
{% load static %}


{% block title %} {{article.title}} | {{block.super}}{% endblock %}

{% block content %}
<!-- <h3 class="pb-4 mb-4 font-italic border-bottom">
From the Firehose
</h3> -->
<div class="blog-post">
	<h2 class="blog-post-title">{{article.title}}</h2>
	<p class="blog-post-meta">{{article.timestamp|date:"D d M Y"}} by <a href="{% url 'core:user_article' article.user %}">{{article.user}}</a></p>
	<div>
		<div class="video-container">
			<iframe src="https://www.youtube.com/embed/{{article.detail}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" class="youtube-video" allowfullscreen></iframe>
		</div>
	</div> <!-- /.youtube player -->

</div><!-- /.blog-post -->
{% endblock %}

core/templates/core/choose_new_post_type.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Choose new Submission | Simple wedding Movement
{% endblock %}

{% block head_extras %}
<style type="text/css">
  .item-box{
    margin-bottom: 30px;
    padding: 20px;
    border-radius: 5px;
    outline-color: #dddddd;
  }

  .item-box:hover{
    box-shadow: 0px 5px 5px #84CD99;
  }

</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5" style="color: #565656">New Submission</h1>
      <p class="lead">Choose what you want to submit</p>
    </div>
  </div>
</div>



<section class="col-lg-6 offset-lg-3 col-sm-12 col-md-12">
  <div>
    <div class="row item-box">
      <p class="disabled">
        <h2>Article Title</h2>
        <p style="color: grey" class="lead"><b>Coming soon.</b><br>
        Submit An article idea or suggestion. Anyone can write articles on the topics you suggest</p>
      </[>
    </div>
    <div class="row item-box">
      <a href="#" data-toggle="modal" data-target="#newArticle">
        <h2>Article</h2>
        <p class="lead">Write an Article on any topic.</p>
      </a>
    </div>
    <div class="row item-box">
      <a href="{% url 'core:new_link' %}">
        <h2>Link</h2>
        <p class="lead">Submit Links to display on the articles page</p>
      </a>
    </div>
  </div>
</section>



<!-- Button trigger modal -->
<!-- 
<button type="button" class="btn btn-primary" >
  Launch demo modal
</button>
-->

<!-- Modal -->
<div class="modal fade" id="newArticle" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">The article topic</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div>

        <div class="modal-body">
          <div class="row item-box">
            <a href="{% url 'core:new_blog' %}">
              <h2>New topic</h2>
            </a>
          </div>
          <div class="row item-box disabled">
            <p class="disabled">
              <h2 style="color: gray;">Pick title from suggestions</h2>
            </p>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

core/templates/core/new_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Submit New Article | Simple wedding Movement
{% endblock %}

{% block head_extras %}
{{ form.media }}
<style type="text/css">
  .wmd-button-bar{
    background-color: white !important;
  }
  .wmd-panel {
    margin-left: 0% !important;
    margin-right: 0% !important;
    width: 100% !important;
  }
</style>
{% endblock %}


{% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5" style="color: #565656">Submit new Article</h1>
    </div>
  </div>
</div>

<section class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1 col-md-8 offset-md-2">

  <div class="card">
    <div class="card-body">
      <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='btn btn-default' value='Submit'/>
      </form>
    </div>
  </div>
</section>


{% endblock %}