core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    # user views 
    # path('', TemplateView.as_view(template_name='welcome.html'), name='index'),
    # path('', TemplateView.as_view(template_name='base_v2.html'), name='index'),
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.article, name='article'),
    
    # writer views
    path('user/<str:username>', views.user_article, name='user_article'),
    path('blog/new/blog', views.new_blog, name='new_blog'),
    path('blog/new/link', views.new_link, name='new_link'),
	path('blog/new/choose', views.choose_new_post_type, name='choose_new_post_type'),
    path('blog/<slug:slug>/add_meta', views.blog_meta_description, name='blog_meta_description'),

    # Admin views
    path('blog/review', views.review_list, name='review_list'),
    path('blog/<slug:slug>/edit', views.edit_blog, name='edit_blog'),
	path('blog/<slug:slug>/review', views.review, name='review_article'),

    # users

]

usersite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from django.views.generic.base import TemplateView
from core.views import post_api, quran_api#, catagory_api
from core.api.views import QuranAPIView

from accounts.views import (login_view, logout_view, register_view, telegram_bot)

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()

router.register('post', post_api, basename='post_api')
router.register('quran', quran_api, basename='quran_api')

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    
    # VISITOR INTERFACE
    path('quran/', include('core.api.urls', namespace='quran-view')),
    # path('quran/<slug:slug>/', QuranAPIView.as_view(), name='quran-view'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),    
    
    path('faq_v1/', TemplateView.as_view(template_name='faq.html'), name='faq_v1'),
    path('faq/', TemplateView.as_view(template_name='faq_v2.html'), name='faq_v2'),
    path('media/', TemplateView.as_view(template_name='media.html'), name='media'),
    path('about/', TemplateView.as_view(template_name='about_us_v2.html'), name='about'),
    path('roadmap/', TemplateView.as_view(template_name='roadmap_v2.html'), name='roadmap'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact'),
    
    # testing
    # path('login_v2/', TemplateView.as_view(template_name='accounts/login_v2.html'), name='base_v2'),

    # ADMIN INTERFACE
    path('login/',login_view, name='login' ),    
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('admin/', admin.site.urls),

    path('dashboard/', include('accounts.urls', namespace='dashboard')),

    # TELEGRAM BOT
    path('tbot/', telegram_bot, name='telegram_bot'),    

    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from .models import Post, catagories
from pagedown.widgets import PagedownWidget
from django.core.validators import URLValidator



class ArticleForm(forms.ModelForm):
    title = forms.CharField()
    detail = forms.CharField(widget=PagedownWidget())
    # tags = forms.ModelMultipleChoiceField(queryset = taggers.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Post
        fields = [
            "title",
            "detail",
            # "tags"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        article_placeholder = '''       Start writing Your Article Here
        
        How to Format!
        ## for Heading
        ### for subheading

        Example 

        ## how to bake
        ### Start here
        ### follow the list
        1. item 1
        2. item 3
        3. item 3
        '''
        self.fields['title'].widget.attrs['placeholder'] = 'The Title'
        self.fields['detail'].widget.attrs['placeholder'] = article_placeholder


class MetaTagForm(forms.ModelForm):
    meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

class ReviewArticle(forms.ModelForm):
    title = forms.CharField()
    meta_description = forms.CharField(widget=forms.Textarea)
    detail = forms.CharField(widget=PagedownWidget())
    # tags = forms.ModelMultipleChoiceField(queryset = taggers.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Post
        fields = [
            "title",
            "meta_description",
            "detail",
            "publish",
            # "tags"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        article_placeholder = '''       Start writing Your Article Here
        
        How to Format!
        ## for Heading
        ### for subheading

        Example 

        ## how to bake
        ### Start here
        ### follow the list
        1. item 1
        2. item 3
        3. item 3
        '''
        self.fields['title'].widget.attrs['placeholder'] = 'The Title'
        self.fields['detail'].widget.attrs['placeholder'] = article_placeholder
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

class LinkForm(forms.ModelForm):
    # title = forms.CharField()
    link = forms.CharField()
    # meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            # "title", <-- Will be parsed by 
            "link",
            # "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].widget.attrs['placeholder'] = "Paste your link here with https:// or http://"
        # self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"


class ReviewLink(forms.ModelForm):
    title = forms.CharField()
    link = forms.CharField()
    meta_description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = [
            "title",
            "link",
            "meta_description",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].widget.attrs['placeholder'] = "Paste your link here"
        self.fields['title'].widget.attrs['placeholder'] = "Write the title"
        self.fields['meta_description'].widget.attrs['placeholder'] = "Enter Short Description. Less than 160 Characters"

templates/about_us_v2.html
{% extends 'base_v2.html' %}
{% load static %}


{% block title %} About {{block.super}}{% endblock %}

{% block head_extras %}{% endblock %}

{% block content %}

<h3 class="pb-4 mb-4 font-italic border-bottom">
	About us
</h3>

<div class="row blog-post">
	<div>
		
		<h2 class="blog-post-title">Who are we</h2>
		<p class="blog-post-meta lead">Detailed explanation</p>
		
	</div>
</div>
<div class="row blog-post">
	<div>
		
		<h2 class="blog-post-title">What are we doing</h2>
		<p class="blog-post-meta lead">Detailed explanation</p>
		
	</div>
</div>
<div class="row blog-post">
	<div>
		
		<h2 class="blog-post-title">Source of Information</h2>
		<p class="blog-post-meta lead">Detailed explanation</p>
		
	</div>	
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}Simple wedding Movement{% endblock %}</title> <!-- MAX 70 Chars-->
	{% block meta_tags %}{% endblock %}

	<!-- Favicons -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
	
	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/4af485e413.js" crossorigin="anonymous"></script>

	<!-- Bootstrap core CSS -->
	{% block head_extras %}{% endblock %}
	<!-- Bootstrap core CSS -->
	<!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	{% if production %}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158060116-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-158060116-1');
	</script>
	{% endif %}

	<style type="text/css">
		html {
			position: relative;
			min-height: 100%;
		}
		.link-box{
			background-color: #FFFFFF;
		}
		.extra-text{
			color: #A8A8A8;
		}
		#content {
			padding-bottom: 50px;
			background-color: {% if article.publish == False %} #F4B9AD {% else %} #CCEAD4 {% endif%}; 
		}
	</style>
</head>

<body>

	<!-- Navigation -->
	{% include 'navbar.html' %}

	<div id="content">
		<!-- Page Content -->
		{% block content %}
		{% endblock %}
	</div>

	<!-- Footer -->
	{% include 'footer.html' %}

	<!-- Bootstrap core JavaScript -->
	<!-- <script src="vendor/jquery/jquery.slim.min.js"></script> -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<!-- <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.2/marked.min.js" integrity="sha256-6Om9HYjLO4iZmEyM/7oAv7GW1WzACqQ4PV51bTgnioI=" crossorigin="anonymous"></script>

	<script type="text/javascript">
		$(document).ready(function(){
			// making the content space full height. fill up device;'s space.
			var screen_height = screen.height + "px"
			document.getElementById("content").style.minHeight = screen_height;

			// content markdown for blogs details and blog editor preview
			$('.content-markdown').each(function(){
				var content = $(this).text()
				var markedContent = marked(content);
				$(this).html(markedContent)
				$("#preview-content img").each(function(){
					$(this).addClass('custom-img-responsive');
				});
			})

			var titleInput = $("#id_title")
			function setTitle(value){
				$("#preview-title").text(value)
			}

			setTitle(titleInput.val())
			titleInput.keyup(function(){
				var newTitle = $(this).val()
				setTitle(newTitle)
			})


			var contentInput = $("#wmd-input-id_detail")
			function setContent(value){
				var markedContent = marked(value)
				$("#preview-content").html(markedContent)
				$("#preview-content img").each(function(){
					$(this).addClass('img-responsive')
				})
			}
			setContent(contentInput.val())
			contentInput.keyup(function(){
				var newContent = $(this).val()
				setContent(newContent)
			})

			
		})
	</script>
	{% comment %}
	{% if request.resolver_match.url_name == 'blog_meta_description' %}
	<!-- enter script to count meta-description's length -->
	{% endif %}
	{% endcomment %}

</body>

</html>

templates/base_v2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<!-- <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"> -->
	
	<title>{% block title %}Simple Wedding Movement{% endblock %}</title>


	{% block meta_tags %}{% endblock %}

	<!-- Favicons -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
	
	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/4af485e413.js" crossorigin="anonymous"></script>

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	{% block head_extras %}{% endblock %}
	<link href="https://fonts.googleapis.com/css2?family=Katibeh&display=swap" rel="stylesheet">
	<style type="text/css">

		.arabic-text{
			font-family: 'Katibeh', cursive;
			font-size: 40px;
		}

		.bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
		}

		@media (min-width: 768px) {
			.bd-placeholder-img-lg {
				font-size: 3.5rem;
			}
		}
		
		.video-container {
			position: relative;
			width: 100%;
			height: 0;
			padding-bottom: 56.25%;
			margin-bottom: 30px;
		}
		.youtube-video {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}
	</style>
	<!-- Custom styles for this template -->
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
	<!-- Custom styles for this template -->
	<link href="{% static 'base_v2/blog.css' %}" rel="stylesheet">

	{% if production %}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158060116-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-158060116-1');
	</script>
	{% endif %}

</head>
<body>
	<div class="container">
		<!-- Collective Header -->
		<!-- navbar -->
		{% include 'navbar_v2.html' %}

		<!-- Picker -->
		{% include 'picker_v2.html' %}

		<!-- website content -->
		{% block welcome_content %}
		{% endblock %}
	</div>

	<main role="main" class="container">
		<div class="row">
			<div id='content' class="col-md-8 blog-main">
				{% block content %}
				{% endblock %}
			</div><!-- /.blog-main -->

			<aside class="col-md-4 blog-sidebar">
				{% include 'snippet_about_us_v2.html' %}
				<!-- {% include 'snippet_archives_v2.html' %} -->
				<!-- {% include 'snippet_social_v2.html' %} -->
			</aside><!-- /.blog-sidebar -->

		</div><!-- /.row -->

	</main><!-- /.container -->

	<!-- Footer -->
	<div class="col-12 blog-footer">
		{% include 'footer.html' %}
	</div><!-- /.Footer -->
	<!-- Bootstrap core JavaScript -->
	<!-- <script src="vendor/jquery/jquery.slim.min.js"></script> -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<!-- <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<!-- 	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.2/marked.min.js" integrity="sha256-6Om9HYjLO4iZmEyM/7oAv7GW1WzACqQ4PV51bTgnioI=" crossorigin="anonymous"></script>
	-->
	<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js' type="text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.0.11/purify.min.js" type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

	<script type="text/javascript">
		$(document).ready(function(){
			// convert Q2:255 mentions into quran text.
			// DONE 1. use regex to find all mentions
			// DONE 2. get the numbers 2:225
			// DONE 3. fetch API http://api.alquran.cloud/v1/ayah/2:255
			// 4. store api into custom DM
			// DONE 5. replace text Q2:255 into arabic text
			var quran_regex = /Q([0-9]:[0-9])\w+/g;

			// document.body.innerHTML = document.body.innerHTML.replace(quran_regex, "Quran text here");
			
			// ENABLE THIS TO TEST
			document.body.innerHTML = document.body.innerHTML.replace(quran_regex, aiyath_writer);

			function aiyath_writer(aiyath) {
				// within the function, start a fetch api
				var arabic_text;
				// an ajax api fetch
				$.ajax({

					type: "GET", // set the type, url and dataType
					async: false, // solved the async issue with this short solution. refer the same page to get complete clarity.
					// https://stackoverflow.com/questions/13848123/jquery-return-value-undefined
					
					url: 'http://api.alquran.cloud/v1/ayah/'+aiyath.replace(/[Q]/,''),
					dataType: "json",
					// if success, do the following function
					success: function (data) {
						arabic_text = data['data']['text']
						console.log(arabic_text); // <= this works
						
					},
					// if error, log it.
					error: function (error) {
						console.log(error);
						return error;
					}
				});
				
				return_format = '<p class="arabic-text" dir="rtl" lang="ar">'+arabic_text+'</p>'
				
				return return_format
			}


			// making the content space full height. fill up device;'s space.
			var screen_height = screen.height + "px";
			// console.log(screen_height);
			document.getElementById("content").style.minHeight = screen_height;

			// content markdown for blogs details and blog editor preview
			$('.content-markdown').each(function(){



				var content = $(this).text()
				// console.log(content);
				var converter = new showdown.Converter();
				// var markedContent = marked(content); /*not using marked*/
				html = converter.makeHtml(content);
				// console.log(html);
				var sanitisedMarkedContent = DOMPurify.sanitize(html);
				// console.log(sanitisedMarkedContent);

				// $(this).innerHTML(sanitisedMarkedContent)
				$(this).html(sanitisedMarkedContent);
				// console.log(sanitisedMarkedContent)
				$("#preview-content img").each(function(){
					$(this).addClass('custom-img-responsive');
				});
			})

			var titleInput = $("#id_title")
			function setTitle(value){
				$("#preview-title").text(value)
			}

			setTitle(titleInput.val())
			titleInput.keyup(function(){
				var newTitle = $(this).val()
				setTitle(newTitle)
			})


			var contentInput = $("#wmd-input-id_detail")
			function setContent(value){
				var markedContent = marked(value)
				$("#preview-content").html(markedContent)
				$("#preview-content img").each(function(){
					$(this).addClass('img-responsive')
				})
			}
			setContent(contentInput.val())
			contentInput.keyup(function(){
				var newContent = $(this).val()
				setContent(newContent)
			})
			
		})
	</script>
</body>
</html>

templates/media.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Media Mentions | Simple wedding Movement
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5" style="color: #565656">Media Mentions</h1>
      <p class="lead">list of publications talking about the Simple Shadi Movement</p>
    </div>
  </div>
</div>

<section class="col-lg-6 offset-lg-3 col-sm-12 col-md-12">
  <p class="lead">coming soon...</p>
  <!-- <div class="list-group list-group-flush">
    
  </div> -->
</section>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'core:index' %}">
      <img src="{% static 'favicons/favicon-32x32.png' %}" width="32" height="32" alt="Simple Wedding Movement Logo">
      <!-- Simple Wedding Movement -->
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-left">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>&nbsp;{{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'core:user_article' request.user %}"><i class="fas fa-id-card"></i>&nbsp;My Article</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'core:choose_new_post_type' %}"><i class="fas fa-plus"></i>&nbsp;Submit New</a>
          {% if request.user.is_staff %}
          <a class="dropdown-item" href="{% url 'core:review_list' %}"><i class="fas fa-tasks"></i>&nbsp;Review Submission</a>
          {% endif %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
          <a class="nav-link" role="button" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;Login</a>
        </li>
      {% endif %}
                
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.resolver_match.url_name == 'faq' %}active{% endif %}">
          <a class="nav-link" href="{% url 'faq_v2' %}"><i class="fas fa-question"></i>&nbsp;FAQ</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'about' %}active{% endif %}">
          <a class="nav-link" href="{% url 'about' %}"><i class="fas fa-users"></i>&nbsp;About Us</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
          <a class="nav-link" href="{% url 'contact' %}"><i class="fas fa-phone-alt"></i>&nbsp;Contact Us</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'media' %}active{% endif %}">
          <a class="nav-link" href="{% url 'media' %}"><i class="fas fa-newspaper"></i>&nbsp;Media</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'blog' %}active{% endif %}">
          <a class="nav-link btn btn-primary" role="button" href="{% url 'core:blog' %}"><i class="fas fa-book-reader"></i>&nbsp;Read Article</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/picker_v2.html
{% load static %}
<div class="nav-scroller py-1 mb-2">
	<nav class="nav d-flex justify-content-between">
		<a class="p-2 text-muted" href="{% url 'core:blog' %}">Blog</a>
		<a class="p-2 text-muted" href="{% url 'faq_v2' %}">FAQs</a>
		<a class="p-2 text-muted" href="{% url 'about' %}">About us</a>
		<!-- <a class="p-2 text-muted" href="{% url 'contact' %}">Contact us</a> -->
		<p class="p-2 text-muted">Contact us</p>
		<p class="p-2 text-muted">Media</p>
		<!-- <a class="p-2 text-muted" href="{% url 'media' %}">Media</a> -->
		<a class="p-2 text-muted" href="http://www.khalifatullahmehdi.info/">Khalifatullah Mehdi</a>
		<!-- <a class="p-2 text-muted" href="#">Core Principles</a> -->
		<p class="p-2 text-muted">Core Principles</p>
		<a class="p-2 text-muted" href="{% url 'roadmap' %}">RoadMap</a>
		<!-- <a class="p-2 text-muted" href="#">name</a> -->

	</nav>
</div>